version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
  celery:
    format: "%(asctime)s - %(levelname)s - %(processName)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  celery-console:
    class: logging.StreamHandler
    level: INFO
    formatter: celery
    stream: ext://sys.stdout
loggers:
  prince_archiver:
    level: DEBUG
    handlers: [console]
    propagate: false
  celery:
    level: DEBUG
    handlers: [celery-console]
    propagate: false
root:
  level: DEBUG
  handlers: [console]
