version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
loggers:
  uvicorn:
    level: DEBUG
    handlers: [console]
    propagate: false
  prince_archiver:
    level: DEBUG
    handlers: [console]
    propagate: false
  arq:
    level: DEBUG
    handlers: [console]
    propagate: false
root:
  level: DEBUG
  handlers: [console]
