version: "3.8"

services:

  image-stitcher:
    image: image-stitcher
    build:
      context: .
    command: ["python", "-m", "image_stitcher.watcher"]
    volumes:
      - ./image_stitcher:/app/image_stitcher/
      - input_data:/data/input
    environment:
      - DATA_DIR=/data/input
      - AWS_ACCESS_KEY_ID=aws-access-key-id
      - AWS_SECRET_ACCESS_KEY=aws-access-key-id
      - AWS_ENDPOINT_URL=http://s3:9090
    platform: linux/amd64

  producer:
    image: image-stitcher
    command: ["python", "-m", "image_stitcher.test_utils"]
    environment:
      - DATA_DIR=/data/input
      - IMG_CACHE=/data/cache
    volumes:
      - img_cache:/data/cache
      - input_data:/data/input
    platform: linux/amd64

  s3:
    image: adobe/s3mock:3.1.0
    ports:
      - 9090:9090
      - 9191:9191
    environment:
      - initialBuckets=fast-stitcher-dev
      - validKmsKeys=arn:aws:kms:eu-central-1:1234567890:key/aws-access-key-id


volumes:
  img_cache:
  input_data:
