---

services: 
  traefik:
    image: traefik:v2.10
    ports:
      - 80:80
      - 8081:8080
    volumes:
      - "./config/traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - traefik.docker.network=traefik-public
    networks:
      - traefik-public


networks:
  traefik-public:
    name: traefik-public
    external: true
