---

services:
  surf-archiver-remote:
    image: mycostreams/surf-archiver-remote:${TAG:-latest}
    build:
      context: .
      target: runtime
    command: ["arq", "surf_archiver.remote.WorkerSettings"]
    environment:
      REDIS_DSN: ${REDIS_DSN}
      USERNAME: ${SURF_USERNAME}
      PASSWORD: ${SURF_PASSWORD}
      SENTRY_DSN: ${SENTRY_DSN}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      logging: loki
      logging_jobname: ${DEPLOYMENT_NAME-:surf-archiver-prod}
    deploy:
      restart_policy:
        condition: on-failure
