version: "3.8"

services:

  watcher:
    environment:
      - SENTRY_DSN
      - WATCHFILES_FORCE_POLLING=true
    labels:
      com.datadoghq.ad.logs: '[{"source": "watcher", "service": "watcher"}]'
    volumes:
      - cifs_mount:/data/input/
    env_file:
      - .env
      - .env.prod
  
  worker:
    environment:
      - SENTRY_DSN
    labels:
      com.datadoghq.ad.logs: '[{"source": "worker", "service": "worker"}]'
    volumes:
      - cifs_mount:/data/input/
    env_file:
      - .env
      - .env.prod

  datadog:
    image: datadog/agent:latest
    pid: host
    environment:
     - DD_API_KEY=${DD_API_KEY}
     - DD_SITE=datadoghq.eu
     - DD_LOGS_ENABLED=true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
     - /var/lib/docker/containers:/var/lib/docker/containers:ro


volumes:
  cifs_mount: 
    driver_opts:
      type: cifs
      device: //prince.amolf.nl/Data/Prince2/Images/
      o: username=${AMOLF_USERNAME},password=${AMOLF_PASSWORD}
