---
name: stream-ingester

services:
  stream-ingester:
    image: mycostreams/prince-archiver:${TAG:-latest}
    build:
      context: .
    command: ["python", "stream_ingester.py"]
    environment: 
      REDIS_DSN: redis://host.docker.internal:6380
    volumes:
      - ./prince_archiver:/app/prince_archiver
      - ./ping.py:/app/ping.py
      - ./stream_ingester.py:/app/stream_ingester.py
    extra_hosts:
          - "host.docker.internal:host-gateway"
