version: "3.8"

services:

  prince:
    volumes:
      - ./prince_archiver:/app/prince_archiver
      - ./alembic:/app/alembic

  watcher:
    volumes:
    - ./prince_archiver:/app/prince_archiver
    - ./alembic:/app/alembic

  worker:
    volumes:
    - ./prince_archiver:/app/prince_archiver
    - ./alembic/:/app/alembic
