version: "3.8"

x-env-variables: &env-variables
  DATA_DIR: /data/input/
  ARCHIVE_DIR: /data/archive/
  TEMP_FILE_DIR: /data/tmp/
  CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672/
  POSTGRES_DSN: postgresql://postgres:postgres@db:5432/postgres

services:

  watcher:
    image: prince-archiver
    environment: *env-variables
    command: ["python", "-m", "prince_archiver.entrypoints.watcher"]
    volumes:
    - input_data:/data/input
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  worker:
    image: prince-archiver
    command: ["celery", "-A", "prince_archiver.celery", "worker", "-l", "INFO"]
    environment: *env-variables
    volumes:
    - input_data:/data/input
    - archive_data:/data/archive
    - temp_data:/data/tmp
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=amqp://guest:guest@rabbitmq:5672/', '--port=5555']
    ports:
      - 5557:5555
    depends_on:
      rabbitmq:
        condition: service_healthy


volumes:
  input_data:
  archive_data:
  temp_data:
  postgres_data:
