version: "3.8"

x-env-variables: &env-variables
  DATA_DIR: /data/input/
  REDIS_DSN: redis://redis:6379


services:

  watcher:
    image: prince-archiver
    build:
      context: .
    environment: 
      <<: *env-variables
      POSTGRES_DSN: postgresql+asyncpg://postgres:postgres@db:5432/postgres
    command: ["python", "-m", "prince_archiver.entrypoints.watcher"]
    volumes:
    - input_data:/data/input
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  worker:
    image: prince-archiver
    command: ["arq", "prince_archiver.worker.WorkerSettings"]
    environment: *env-variables
    volumes:
    - input_data:/data/input
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7.2.4
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  input_data:
  postgres_data:
