---
x-aws-env-variables: &aws-env-variables
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  AWS_ENDPOINT_URL: https://proxy.swift.surfsara.nl
  AWS_REGION_NAME: NL


x-log-labels: &log-labels
  logging: loki
  logging_jobname: ${DEPLOYMENT_NAME-:morricone}


services:
  watcher:
    environment:
      SENTRY_DSN: ${SENTRY_DSN}
      WATCHFILES_FORCE_POLLING: "true"
    volumes:
      - cifs_mount:/data/input/
    labels: *log-labels
    deploy:
      restart_policy:
        condition: on-failure
  
  upload-worker:
    environment:
      <<: *aws-env-variables
      SENTRY_DSN: ${SENTRY_DSN}
      AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
    volumes:
      - cifs_mount:/data/input/:ro
    labels: *log-labels
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  cron-worker:
    environment:
      <<: *aws-env-variables
      SURF_USERNAME: ${SURF_USERNAME}
      SURF_PASSWORD: ${SURF_PASSWORD}
      SENTRY_DSN: ${SENTRY_DSN}
      UPLOAD_EXPIRY_DAYS: ${UPLOAD_EXPIRY_DAYS:-5}
      ARCHIVE_TRANSITION_DAYS: ${ARCHIVE_TRANSITION_DAYS:-2}
    labels: *log-labels
    deploy:
      restart_policy:
        condition: on-failure

  data-archive-subscriber:
    environment:
      SENTRY_DSN: ${SENTRY_DSN}
      RABBITMQ_DSN: ${RABBITMQ_DSN}
    labels: *log-labels
    deploy:
      restart_policy:
        condition: on-failure

  alloy:
    image: grafana/alloy:latest
    command:
      - "run"
      - "/etc/alloy/config.alloy"
      - "--server.http.listen-addr=0.0.0.0:12345"
      - "--storage.path=/var/lib/alloy/data"
    environment:
      PROM_USERNAME: ${PROM_USERNAME}
      LOKI_USERNAME: ${LOKI_USERNAME}
      GRAFANA_API_TOKEN: ${GRAFANA_API_TOKEN}
    volumes:
      - ./config/config.alloy:/etc/alloy/config.alloy
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run:/var/run:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    privileged: true
    ports:
      - 12345:12345
    networks:
      - monitoring

volumes:
  cifs_mount: 
    driver_opts:
      type: cifs
      device: //prince.amolf.nl/Data/Prince2/Images/
      o: username=${AMOLF_USERNAME},password=${AMOLF_PASSWORD}

networks:
  monitoring: 
