version: "3.8"

services:

  watcher:
    environment:
      - SENTRY_DSN=${SENTRY_DSN}
      - WATCHFILES_FORCE_POLLING=true
    labels:
      logging: "promtail"
    volumes:
      - cifs_mount:/data/input/
    env_file:
      - .env
      - .env.prod
    restart: always
  
  worker:
    environment:
      - SENTRY_DSN=${SENTRY_DSN}
    labels:
      logging: "promtail"
    volumes:
      - cifs_mount:/data/input/
    env_file:
      - .env
      - .env.prod
    restart: always

  cron-worker:
    image: prince-archiver
    command: ["arq", "prince_archiver.data_archive.WorkerSettings"]
    environment:
      - REDIS_DSN=redis://redis:6379
    labels:
      logging: "promtail"
    env_file:
      - .env
      - .env.prod
    depends_on:
      redis:
        condition: service_healthy

  promtail:
    image:  grafana/promtail:latest
    container_name: promtail
    environment:
      - LOKI_USERNAME=${LOKI_USERNAME}
      - LOKI_API_TOKEN=${LOKI_API_TOKEN}
    volumes:
      - ./config/promtail.yaml:/etc/promtail/docker-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml -config.expand-env=true


volumes:
  cifs_mount: 
    driver_opts:
      type: cifs
      device: //prince.amolf.nl/Data/Prince2/Images/
      o: username=${AMOLF_USERNAME},password=${AMOLF_PASSWORD}
