version: "3.8"

x-celery-variables: &celery-variables
  DATA_DIR: /data/input
  ARCHIVE_DIR: /data/output
  CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672/
  AWS_ACCESS_KEY_ID: aws-access-key-id
  AWS_ENDPOINT_URL: http://s3mock:9090
  POSTGRES_DSN: postgresql://postgres:postgres@postgres:5432/postgres

services:

  watcher:
    build:
      context: .
    environment: *celery-variables
    command: ["python", "-m", "prince_archiver.main"]
    volumes:
    - ./data:/data/
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "prince_archiver.celery", "worker", "-l", "INFO"]
    environment: *celery-variables
    volumes:
      - ./data:/data/
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=amqp://guest:guest@rabbitmq:5672/', '--port=5555']
    ports:
      - 5557:5555
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  s3mock:
    image: adobe/s3mock:3.1.0
    ports:
      - 9090:9090
      - 9191:9191
    environment:
      - initialBuckets=mycostreams
      - validKmsKeys=arn:aws:kms:eu-central-1:1234567890:key/aws-access-key-id
  
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
