version: "3.8"

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "prince.celery_app", "worker", "-l", "INFO"]
    environment:
      - DATA_DIR=/data/input
      - ARCHIVE_DIR=/data/output
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
    volumes:
      - ./data:/data/
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - 5672:5672
      - 15672:15672
  
  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=amqp://guest:guest@rabbitmq:5672/', '--port=5555']
    ports:
      - 5557:5555
    depends_on:
      - rabbitmq
