name: prince-archiver
on:
  pull_request:
    paths: 
      - 'prince-archiver/**'
      - '.github/workflows/prince-archiver.yaml'

defaults:
  run:
    working-directory: ./prince-archiver

jobs:
  static-analysis:
    name: Static analysis
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry
      - name: Install dependencies
        run: poetry install 
      - name: Run black
        run: poetry run black . --check
      - name: Run isort
        run: poetry run isort . --check-only
      - name: Run flake8
        run: poetry run flake8 .
      - name: Run mypy
        run: poetry run mypy .
  
  unit-tests:
    name: Unit tests
    needs: static-analysis
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.12"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install dependencies
        run: |
          poetry env use ${{ matrix.python-version }} 
          poetry install
      - name: Unit tests
        run: poetry run pytest tests/unit

  integration-tests:
    name: Integration tests
    needs: unit-tests
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry
      - name: Install dependencies
        run: poetry install
      - name: Run
        run: ./scripts/run-integration-tests.sh
  
  e2e-tests:
    name: E2E tests
    needs: integration-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./scripts/run-e2e-tests.sh
