name: prince-stitcher
on:
  pull_request:
    paths: 
      - 'prince-stitcher/**'
      - '.github/workflows/prince-stitcher.yaml'
  push:
    branches:
      - main
    paths: 
      - 'prince-stitcher/**'
      - '.github/workflows/prince-stitcher.yaml'

defaults:
  run:
    working-directory: ./prince-stitcher

jobs:
  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Linting
        uses: chartboost/ruff-action@v1
      - name: Formating
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: ./scripts/run-tests.sh
